image:
  - macOS
  - Visual Studio 2015
  
platform:
  - x86
  - x64

branches:
  only:
    - master

build:
  verbosity: detailed

configuration:
  - Release
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)

for:
  -
    matrix:
      only:
        - image: macOS
  
    install:
     - git submodule update --init --recursive
     - brew install qt5
     - export PATH="/usr/local/opt/qt/bin:$PATH"
     - export LDFLAGS="-L/usr/local/opt/qt/lib"
     - export CPPFLAGS="-I/usr/local/opt/qt/include"
     - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

    before_build:
      - cmake --version
      - qmake -v
      - mkdir build
      - cd build
        cmake ..

    build_script:
      - cmake --build . --config %CONFIGURATION%

    after_build:
       - ls

    artifacts:
       - path: build
   
# override settings for Visual Studio 2015
  -
    matrix:
      only:
        - image: Visual Studio 2015
        
    environment:
      artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)

    before_build:
      - if [%PLATFORM%]==[x64] (
        set QT5=C:\Qt\5.11\msvc2015_64)
      - if [%PLATFORM%]==[x86] (
        set QT5=C:\Qt\5.11\msvc2015)
      - set PATH=%PATH%;%QT5%\bin;%QT5%\lib\cmake
      - set Qt5Core_DIR=%QT5%
      - mkdir build
      - cd build
      - if [%env_arch%]==[x64] (
        cmake .. -A x64 )
      - if [%env_arch%]==[x86] (
        cmake .. )

    build_script:
      - cmake --build . --config %CONFIGURATION%

    after_build:
      - mkdir %artifactName%
      - cp -r commander/%CONFIGURATION%/* %artifactName%
      - cp %QT5%/bin/Qt5Core.dll %artifactName%

    artifacts:
      - path: build\%artifactName%
