os:
  - macos

platform: x64
  - x64

branches:
  only:
    - master
   
install:
- git submodule update --init --recursive
- brew install qt5
- export PATH="/usr/local/opt/qt/bin:$PATH"
- export LDFLAGS="-L/usr/local/opt/qt/lib"
- export CPPFLAGS="-I/usr/local/opt/qt/include"
- export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

build:
  verbosity: detailed

configuration:
  - Release
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"

before_build:
  - cmake --version
  - qmake -v
    
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
