os:
  - macos

platform: x64
  - x64

branches:
  only:
    - master
   
install:
- git submodule update --init --recursive
- brew install qt5

build:
  verbosity: detailed

configuration:
  - Release
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"

before_build:
  - cmake --version
  - qmake -v
    
build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  
