language: cpp
sudo: true

os:
  - osx
    
compiler:
  - clang

addons:
  apt:
    packages:
      - qt5

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
  
before_script:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
