language: cpp

os:
  - osx
  - linux
    
compiler:
  - gcc
  - clang

env:
- QT_VERSION=4
- QT_VERSION=5

addons:
  apt:
    packages:
    - qt5-default
    - qt5-qmake
        
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update-reset;
      brew upgrade cmake -v;
      - |
        if [ "$QT_VERSION" == "4" ]; then
          brew tap cartr/qt4
          brew tap-pin cartr/qt4
          brew install qt@4
        fi
      - |
        if [ "$QT_VERSION" == "5" ]; then
          brew install qt5
        fi
      export PATH="/usr/local/opt/qt/bin:$PATH";
      export LDFLAGS="-L/usr/local/opt/qt/lib";
      export CPPFLAGS="-I/usr/local/opt/qt/include";
      export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
    else
      apt-get install qt4-default;
      apt-get install qt4-qmake;
    fi
    
before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - if [ "$QT_VERSION" == "4" ]; then
    cmake -D USE_QT4=ON ..
    fi
  - cd build
  - if [ "$QT_VERSION" == "5" ]; then
    cmake -D USE_QT4=OFF ..
    fi
  - cmake --build .
  - cd ..
