language: cpp

os:
  - osx
  - linux
    
compiler:
  - gcc

addons:
  apt:
    packages:
      - qt5-default
      - qt5-qmake

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update-reset
    brew upgrade cmake -v
    brew install qt5
    export PATH="/usr/local/opt/qt/bin:$PATH"
    export LDFLAGS="-L/usr/local/opt/qt/lib"
    export CPPFLAGS="-I/usr/local/opt/qt/include"
    export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
    fi
  
before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
