language: cpp

os:
  - osx
  - linux
    
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - qt4-default
      - qt4-default

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update-reset;
      brew upgrade cmake -v;
      brew install qt4;
      export PATH="/usr/local/opt/qt/bin:$PATH";
      export LDFLAGS="-L/usr/local/opt/qt/lib";
      export CPPFLAGS="-I/usr/local/opt/qt/include";
      export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig";
    fi
    
before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake -D USE_QT4=ON ..
  - cmake --build .
  - cd ..
