language: cpp
sudo: true

os:
  - macos
    
compiler:
  - gcc
  - clang

addons:
  brew:
    packages:
      - qt5

before_script:
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
