language: cpp
sudo: true

os:
  - osx
    
compiler:
  - gcc

before_install:
  - brew update-reset
  - brew install qt5
  - export PATH="/usr/local/opt/qt/bin:$PATH"
  - export LDFLAGS="-L/usr/local/opt/qt/lib"
  - export CPPFLAGS="-I/usr/local/opt/qt/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
  
before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
